### data cleaning and preparation

In [2]:
import numpy as np
import pandas as pd

In [3]:
# handling missing data
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [6]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [7]:
float_data = pd.Series([1, 2, None], dtype = "float64")
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.],
                     [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan],
                     [np.nan, 6.5, 3]])

data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [12]:
data.dropna(how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  1.811550       NaN       NaN
1 -0.310931       NaN       NaN
2 -0.189695       NaN -0.320683
3 -0.206400       NaN  0.029074
4  0.342256 -1.284392 -0.154332
5  2.082642 -1.580444 -1.667767
6 -1.507219  1.517208  0.774954

In [14]:
df.dropna()

0         1         2
4  0.342256 -1.284392 -0.154332
5  2.082642 -1.580444 -1.667767
6 -1.507219  1.517208  0.774954

In [15]:
df.dropna(thresh = 2)

0         1         2
2 -0.189695       NaN -0.320683
3 -0.206400       NaN  0.029074
4  0.342256 -1.284392 -0.154332
5  2.082642 -1.580444 -1.667767
6 -1.507219  1.517208  0.774954

In [16]:
df.fillna(0)

0         1         2
0  1.811550  0.000000  0.000000
1 -0.310931  0.000000  0.000000
2 -0.189695  0.000000 -0.320683
3 -0.206400  0.000000  0.029074
4  0.342256 -1.284392 -0.154332
5  2.082642 -1.580444 -1.667767
6 -1.507219  1.517208  0.774954

In [17]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  1.811550  0.500000  0.000000
1 -0.310931  0.500000  0.000000
2 -0.189695  0.500000 -0.320683
3 -0.206400  0.500000  0.029074
4  0.342256 -1.284392 -0.154332
5  2.082642 -1.580444 -1.667767
6 -1.507219  1.517208  0.774954

In [18]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.820149  0.993742  1.849183
1  1.312196 -0.320564 -0.871642
2  1.151877       NaN -1.171898
3  2.360902       NaN  1.088760
4 -0.108811       NaN       NaN
5 -0.343823       NaN       NaN

In [19]:
df.ffill()

0         1         2
0  0.820149  0.993742  1.849183
1  1.312196 -0.320564 -0.871642
2  1.151877 -0.320564 -1.171898
3  2.360902 -0.320564  1.088760
4 -0.108811 -0.320564  1.088760
5 -0.343823 -0.320564  1.088760

In [20]:
df.ffill(limit = 2)

0         1         2
0  0.820149  0.993742  1.849183
1  1.312196 -0.320564 -0.871642
2  1.151877 -0.320564 -1.171898
3  2.360902 -0.320564  1.088760
4 -0.108811       NaN  1.088760
5 -0.343823       NaN  1.088760

In [21]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [22]:
# data transformation
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [26]:
data.drop_duplicates(["k1", "k2"], keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [27]:
# transforming data using a function or mapping
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [29]:
data["animal"] = data["food"].map(meat_to_animal)

data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [30]:
def get_animal(x):
    return meat_to_animal[x]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [31]:
# replacing values
data = pd.Series([1., -999., 2., -999., -1000., 3.])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [32]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [35]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [36]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [37]:
# renaming axis indexes
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                             index = ["Ohio", "Colorado", "New York"],
                             columns = ["one", "two", "three", "four"])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [40]:
data.index = data.index.map(transform)

data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [41]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [42]:
data.rename(index = {"OHIO": "INDIANA"},
            columns = {"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [43]:
# discretization and binning
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [44]:
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)

age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [45]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [47]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [48]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [49]:
pd.value_counts(age_categories)

C:\Users\chadr\AppData\Local\Temp\ipykernel_6100\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [50]:
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [51]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
data = np.random.uniform(size = 20)
pd.cut(data, 4, precision = 2)

In [52]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision = 2)

quartiles

[(-3.4, -0.66], (0.61, 2.84], (-0.66, -0.018], (0.61, 2.84], (0.61, 2.84], ..., (-0.66, -0.018], (-3.4, -0.66], (-0.66, -0.018], (0.61, 2.84], (-3.4, -0.66]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.4, -0.66] < (-0.66, -0.018] < (-0.018, 0.61] < (0.61, 2.84]]

In [53]:
pd.value_counts(quartiles)

C:\Users\chadr\AppData\Local\Temp\ipykernel_6100\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.4, -0.66]      250
(-0.66, -0.018]    250
(-0.018, 0.61]     250
(0.61, 2.84]       250
Name: count, dtype: int64

In [54]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1]).value_counts()

(-3.393, -1.243]     100
(-1.243, -0.0182]    400
(-0.0182, 1.203]     400
(1.203, 2.843]       100
Name: count, dtype: int64

In [55]:
# detecting and filtering outliers
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020988     0.034806    -0.037513    -0.010420
std       0.997634     0.982821     0.992027     1.026366
min      -2.756201    -3.576453    -3.243368    -3.324377
25%      -0.684499    -0.640678    -0.743103    -0.679097
50%       0.027555     0.020228    -0.071305    -0.011273
75%       0.733087     0.684401     0.656654     0.637900
max       4.151443     3.867611     2.918805     3.106535

In [56]:
col = data[2]

col[col.abs() > 3]

972   -3.243368
Name: 2, dtype: float64

In [57]:
data[(data.abs() > 3).any(axis = "columns")]

0         1         2         3
160 -0.450555 -0.824702 -0.559387  3.077641
229  0.392848  0.563833  1.147443  3.106535
334 -0.932184 -3.576453  0.434940  1.665370
386 -1.691481  3.867611 -0.944272  0.877949
537 -0.790499 -0.343809 -1.233556 -3.200374
578 -0.543867 -0.758249  1.906359  3.002535
753  0.260121  0.092123  1.981535 -3.005552
819 -1.700148 -3.158126 -0.774736 -0.547148
857  4.151443 -0.476544 -0.387223  2.214991
867 -0.175169  0.454574  0.653615 -3.324377
972 -0.594355  2.030973 -3.243368  1.195847

In [58]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019836     0.034673    -0.037270    -0.010076
std       0.993518     0.977350     0.991269     1.024190
min      -2.756201    -3.000000    -3.000000    -3.000000
25%      -0.684499    -0.640678    -0.743103    -0.679097
50%       0.027555     0.020228    -0.071305    -0.011273
75%       0.733087     0.684401     0.656654     0.637900
max       3.000000     3.000000     2.918805     3.000000

In [59]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1 -1.0  1.0 -1.0  1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

In [60]:
# permutation and random sampling
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [61]:
sampler = np.random.permutation(5)
sampler

array([0, 1, 4, 3, 2])

In [62]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [63]:
df.iloc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [64]:
column_sampler = np.random.permutation(7)
column_sampler

array([3, 5, 2, 6, 4, 1, 0])

In [65]:
df.take(column_sampler, axis = "columns")

3   5   2   6   4   1   0
0   3   5   2   6   4   1   0
1  10  12   9  13  11   8   7
2  17  19  16  20  18  15  14
3  24  26  23  27  25  22  21
4  31  33  30  34  32  29  28

In [66]:
df.sample(n = 3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [68]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n = 10, replace = True)

2   -1
4    4
4    4
1    7
3    6
4    4
2   -1
4    4
4    4
2   -1
dtype: int64

In [69]:
# computing indicator / dummy variables
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [71]:
pd.get_dummies(df["key"], dtype = float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [72]:
dummies = pd.get_dummies(df["key"], prefix = "key", dtype = float)
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [73]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("https://raw.githubusercontent.com/wesm/pydata-book/3rd-edition/datasets/movielens/movies.dat",
                       sep = "::", header = None, names = mnames, engine = "python")

In [77]:
movies.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [79]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [80]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [82]:
np.random.seed(12345) # to make the example repeatable
values = np.random.uniform(size = 10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [83]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [ ]:
# extension data types